// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// DID data transfer object
///
/// Generated class from Pigeon that represents data sent in messages.
struct DidDto {
  var id: String
  var didString: String
  var method: String
  var keyType: String
  var createdAt: String
  var isDefault: Bool
  var metadata: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DidDto? {
    let id = pigeonVar_list[0] as! String
    let didString = pigeonVar_list[1] as! String
    let method = pigeonVar_list[2] as! String
    let keyType = pigeonVar_list[3] as! String
    let createdAt = pigeonVar_list[4] as! String
    let isDefault = pigeonVar_list[5] as! Bool
    let metadata: [String?: Any?]? = nilOrValue(pigeonVar_list[6])

    return DidDto(
      id: id,
      didString: didString,
      method: method,
      keyType: keyType,
      createdAt: createdAt,
      isDefault: isDefault,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      didString,
      method,
      keyType,
      createdAt,
      isDefault,
      metadata,
    ]
  }
}

/// Credential data transfer object
///
/// Generated class from Pigeon that represents data sent in messages.
struct CredentialDto {
  var id: String
  var name: String
  var type: String
  var format: String
  var issuerName: String
  var issuerDid: String? = nil
  var holderDid: String? = nil
  var issuedDate: String
  var expiryDate: String? = nil
  var claims: [String?: Any?]
  var proofType: String? = nil
  var state: String
  var backgroundColor: String? = nil
  var textColor: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CredentialDto? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! String
    let format = pigeonVar_list[3] as! String
    let issuerName = pigeonVar_list[4] as! String
    let issuerDid: String? = nilOrValue(pigeonVar_list[5])
    let holderDid: String? = nilOrValue(pigeonVar_list[6])
    let issuedDate = pigeonVar_list[7] as! String
    let expiryDate: String? = nilOrValue(pigeonVar_list[8])
    let claims = pigeonVar_list[9] as! [String?: Any?]
    let proofType: String? = nilOrValue(pigeonVar_list[10])
    let state = pigeonVar_list[11] as! String
    let backgroundColor: String? = nilOrValue(pigeonVar_list[12])
    let textColor: String? = nilOrValue(pigeonVar_list[13])

    return CredentialDto(
      id: id,
      name: name,
      type: type,
      format: format,
      issuerName: issuerName,
      issuerDid: issuerDid,
      holderDid: holderDid,
      issuedDate: issuedDate,
      expiryDate: expiryDate,
      claims: claims,
      proofType: proofType,
      state: state,
      backgroundColor: backgroundColor,
      textColor: textColor
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      type,
      format,
      issuerName,
      issuerDid,
      holderDid,
      issuedDate,
      expiryDate,
      claims,
      proofType,
      state,
      backgroundColor,
      textColor,
    ]
  }
}

/// Interaction data transfer object
///
/// Generated class from Pigeon that represents data sent in messages.
struct InteractionDto {
  var id: String
  var type: String
  var verifierName: String
  var requestedCredentials: [String?]
  var timestamp: String
  var status: String
  var completedAt: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InteractionDto? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let verifierName = pigeonVar_list[2] as! String
    let requestedCredentials = pigeonVar_list[3] as! [String?]
    let timestamp = pigeonVar_list[4] as! String
    let status = pigeonVar_list[5] as! String
    let completedAt: String? = nilOrValue(pigeonVar_list[6])

    return InteractionDto(
      id: id,
      type: type,
      verifierName: verifierName,
      requestedCredentials: requestedCredentials,
      timestamp: timestamp,
      status: status,
      completedAt: completedAt
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      verifierName,
      requestedCredentials,
      timestamp,
      status,
      completedAt,
    ]
  }
}

/// Result wrapper for operations
///
/// Generated class from Pigeon that represents data sent in messages.
struct OperationResult {
  var success: Bool
  var error: String? = nil
  var data: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OperationResult? {
    let success = pigeonVar_list[0] as! Bool
    let error: String? = nilOrValue(pigeonVar_list[1])
    let data: [String?: Any?]? = nilOrValue(pigeonVar_list[2])

    return OperationResult(
      success: success,
      error: error,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      error,
      data,
    ]
  }
}

private class SsiApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DidDto.fromList(self.readValue() as! [Any?])
    case 130:
      return CredentialDto.fromList(self.readValue() as! [Any?])
    case 131:
      return InteractionDto.fromList(self.readValue() as! [Any?])
    case 132:
      return OperationResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SsiApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DidDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CredentialDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? InteractionDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OperationResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SsiApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SsiApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SsiApiPigeonCodecWriter(data: data)
  }
}

class SsiApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SsiApiPigeonCodec(readerWriter: SsiApiPigeonCodecReaderWriter())
}


/// Main SSI API for native platform communication
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SsiApi {
  /// Initialize the SSI SDK
  func initialize(completion: @escaping (Result<OperationResult, Error>) -> Void)
  /// Get SDK version
  func getVersion() throws -> String
  /// Create a new DID
  func createDid(method: String, keyType: String, completion: @escaping (Result<DidDto?, Error>) -> Void)
  /// Get all DIDs
  func getDids(completion: @escaping (Result<[DidDto], Error>) -> Void)
  /// Get a specific DID by ID
  func getDid(didId: String, completion: @escaping (Result<DidDto?, Error>) -> Void)
  /// Delete a DID
  func deleteDid(didId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Get all credentials
  func getCredentials(completion: @escaping (Result<[CredentialDto], Error>) -> Void)
  /// Get a specific credential by ID
  func getCredential(credentialId: String, completion: @escaping (Result<CredentialDto?, Error>) -> Void)
  /// Accept a credential offer
  func acceptCredentialOffer(offerId: String, holderDidId: String?, completion: @escaping (Result<CredentialDto?, Error>) -> Void)
  /// Delete a credential
  func deleteCredential(credentialId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Check credential status
  func checkCredentialStatus(credentialId: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Process a presentation request
  func processPresentationRequest(url: String, completion: @escaping (Result<InteractionDto?, Error>) -> Void)
  /// Submit a presentation
  func submitPresentation(interactionId: String, credentialIds: [String], completion: @escaping (Result<Bool, Error>) -> Void)
  /// Reject a presentation request
  func rejectPresentationRequest(interactionId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Get interaction history
  func getInteractionHistory(completion: @escaping (Result<[InteractionDto], Error>) -> Void)
  /// Export backup
  func exportBackup(completion: @escaping (Result<[String?: Any?], Error>) -> Void)
  /// Import backup
  func importBackup(backupData: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Get supported DID methods
  func getSupportedDidMethods(completion: @escaping (Result<[String], Error>) -> Void)
  /// Get supported credential formats
  func getSupportedCredentialFormats(completion: @escaping (Result<[String], Error>) -> Void)
  /// Uninitialize SDK
  func uninitialize(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Handle authorization response from EUDI issuer
  /// Called when the app receives the authorization callback deep link
  func handleAuthorizationCallback(authorizationResponseUri: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Get debug logs from the native SDK
  /// Returns the last 1000 lines of logs for debugging
  func getDebugLogs(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SsiApiSetup {
  static var codec: FlutterStandardMessageCodec { SsiApiPigeonCodec.shared }
  /// Sets up an instance of `SsiApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SsiApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize the SSI SDK
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Get SDK version
    let getVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVersionChannel.setMessageHandler(nil)
    }
    /// Create a new DID
    let createDidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.createDid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createDidChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let methodArg = args[0] as! String
        let keyTypeArg = args[1] as! String
        api.createDid(method: methodArg, keyType: keyTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createDidChannel.setMessageHandler(nil)
    }
    /// Get all DIDs
    let getDidsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getDids\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDidsChannel.setMessageHandler { _, reply in
        api.getDids { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDidsChannel.setMessageHandler(nil)
    }
    /// Get a specific DID by ID
    let getDidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getDid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDidChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let didIdArg = args[0] as! String
        api.getDid(didId: didIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDidChannel.setMessageHandler(nil)
    }
    /// Delete a DID
    let deleteDidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.deleteDid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteDidChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let didIdArg = args[0] as! String
        api.deleteDid(didId: didIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteDidChannel.setMessageHandler(nil)
    }
    /// Get all credentials
    let getCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialsChannel.setMessageHandler { _, reply in
        api.getCredentials { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCredentialsChannel.setMessageHandler(nil)
    }
    /// Get a specific credential by ID
    let getCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialIdArg = args[0] as! String
        api.getCredential(credentialId: credentialIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCredentialChannel.setMessageHandler(nil)
    }
    /// Accept a credential offer
    let acceptCredentialOfferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.acceptCredentialOffer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acceptCredentialOfferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let offerIdArg = args[0] as! String
        let holderDidIdArg: String? = nilOrValue(args[1])
        api.acceptCredentialOffer(offerId: offerIdArg, holderDidId: holderDidIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      acceptCredentialOfferChannel.setMessageHandler(nil)
    }
    /// Delete a credential
    let deleteCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.deleteCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialIdArg = args[0] as! String
        api.deleteCredential(credentialId: credentialIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteCredentialChannel.setMessageHandler(nil)
    }
    /// Check credential status
    let checkCredentialStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.checkCredentialStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkCredentialStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialIdArg = args[0] as! String
        api.checkCredentialStatus(credentialId: credentialIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkCredentialStatusChannel.setMessageHandler(nil)
    }
    /// Process a presentation request
    let processPresentationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.processPresentationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      processPresentationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.processPresentationRequest(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      processPresentationRequestChannel.setMessageHandler(nil)
    }
    /// Submit a presentation
    let submitPresentationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.submitPresentation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitPresentationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let interactionIdArg = args[0] as! String
        let credentialIdsArg = args[1] as! [String]
        api.submitPresentation(interactionId: interactionIdArg, credentialIds: credentialIdsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitPresentationChannel.setMessageHandler(nil)
    }
    /// Reject a presentation request
    let rejectPresentationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.rejectPresentationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rejectPresentationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let interactionIdArg = args[0] as! String
        api.rejectPresentationRequest(interactionId: interactionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      rejectPresentationRequestChannel.setMessageHandler(nil)
    }
    /// Get interaction history
    let getInteractionHistoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getInteractionHistory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInteractionHistoryChannel.setMessageHandler { _, reply in
        api.getInteractionHistory { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInteractionHistoryChannel.setMessageHandler(nil)
    }
    /// Export backup
    let exportBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.exportBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportBackupChannel.setMessageHandler { _, reply in
        api.exportBackup { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportBackupChannel.setMessageHandler(nil)
    }
    /// Import backup
    let importBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.importBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let backupDataArg = args[0] as! String
        api.importBackup(backupData: backupDataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      importBackupChannel.setMessageHandler(nil)
    }
    /// Get supported DID methods
    let getSupportedDidMethodsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getSupportedDidMethods\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSupportedDidMethodsChannel.setMessageHandler { _, reply in
        api.getSupportedDidMethods { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSupportedDidMethodsChannel.setMessageHandler(nil)
    }
    /// Get supported credential formats
    let getSupportedCredentialFormatsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getSupportedCredentialFormats\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSupportedCredentialFormatsChannel.setMessageHandler { _, reply in
        api.getSupportedCredentialFormats { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSupportedCredentialFormatsChannel.setMessageHandler(nil)
    }
    /// Uninitialize SDK
    let uninitializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.uninitialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      uninitializeChannel.setMessageHandler { _, reply in
        api.uninitialize { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      uninitializeChannel.setMessageHandler(nil)
    }
    /// Handle authorization response from EUDI issuer
    /// Called when the app receives the authorization callback deep link
    let handleAuthorizationCallbackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.handleAuthorizationCallback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleAuthorizationCallbackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let authorizationResponseUriArg = args[0] as! String
        api.handleAuthorizationCallback(authorizationResponseUri: authorizationResponseUriArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleAuthorizationCallbackChannel.setMessageHandler(nil)
    }
    /// Get debug logs from the native SDK
    /// Returns the last 1000 lines of logs for debugging
    let getDebugLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ssi.SsiApi.getDebugLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDebugLogsChannel.setMessageHandler { _, reply in
        api.getDebugLogs { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDebugLogsChannel.setMessageHandler(nil)
    }
  }
}
