// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.ssi

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * DID data transfer object
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DidDto (
  val id: String,
  val didString: String,
  val method: String,
  val keyType: String,
  val createdAt: String,
  val isDefault: Boolean,
  val metadata: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DidDto {
      val id = pigeonVar_list[0] as String
      val didString = pigeonVar_list[1] as String
      val method = pigeonVar_list[2] as String
      val keyType = pigeonVar_list[3] as String
      val createdAt = pigeonVar_list[4] as String
      val isDefault = pigeonVar_list[5] as Boolean
      val metadata = pigeonVar_list[6] as Map<String?, Any?>?
      return DidDto(id, didString, method, keyType, createdAt, isDefault, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      didString,
      method,
      keyType,
      createdAt,
      isDefault,
      metadata,
    )
  }
}

/**
 * Credential data transfer object
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CredentialDto (
  val id: String,
  val name: String,
  val type: String,
  val format: String,
  val issuerName: String,
  val issuerDid: String? = null,
  val holderDid: String? = null,
  val issuedDate: String,
  val expiryDate: String? = null,
  val claims: Map<String?, Any?>,
  val proofType: String? = null,
  val state: String,
  val backgroundColor: String? = null,
  val textColor: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CredentialDto {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as String
      val format = pigeonVar_list[3] as String
      val issuerName = pigeonVar_list[4] as String
      val issuerDid = pigeonVar_list[5] as String?
      val holderDid = pigeonVar_list[6] as String?
      val issuedDate = pigeonVar_list[7] as String
      val expiryDate = pigeonVar_list[8] as String?
      val claims = pigeonVar_list[9] as Map<String?, Any?>
      val proofType = pigeonVar_list[10] as String?
      val state = pigeonVar_list[11] as String
      val backgroundColor = pigeonVar_list[12] as String?
      val textColor = pigeonVar_list[13] as String?
      return CredentialDto(id, name, type, format, issuerName, issuerDid, holderDid, issuedDate, expiryDate, claims, proofType, state, backgroundColor, textColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      type,
      format,
      issuerName,
      issuerDid,
      holderDid,
      issuedDate,
      expiryDate,
      claims,
      proofType,
      state,
      backgroundColor,
      textColor,
    )
  }
}

/**
 * Interaction data transfer object
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InteractionDto (
  val id: String,
  val type: String,
  val verifierName: String,
  val requestedCredentials: List<String?>,
  val timestamp: String,
  val status: String,
  val completedAt: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InteractionDto {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val verifierName = pigeonVar_list[2] as String
      val requestedCredentials = pigeonVar_list[3] as List<String?>
      val timestamp = pigeonVar_list[4] as String
      val status = pigeonVar_list[5] as String
      val completedAt = pigeonVar_list[6] as String?
      return InteractionDto(id, type, verifierName, requestedCredentials, timestamp, status, completedAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      verifierName,
      requestedCredentials,
      timestamp,
      status,
      completedAt,
    )
  }
}

/**
 * Requested claim details for presentation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RequestedClaimDto (
  val claimName: String,
  val claimPath: String,
  val required: Boolean,
  val purpose: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RequestedClaimDto {
      val claimName = pigeonVar_list[0] as String
      val claimPath = pigeonVar_list[1] as String
      val required = pigeonVar_list[2] as Boolean
      val purpose = pigeonVar_list[3] as String?
      return RequestedClaimDto(claimName, claimPath, required, purpose)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      claimName,
      claimPath,
      required,
      purpose,
    )
  }
}

/**
 * Presentation request details
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PresentationRequestDto (
  val interactionId: String,
  val verifierName: String,
  val verifierUrl: String,
  val verifierLogo: String? = null,
  val requestedClaims: List<RequestedClaimDto?>,
  val matchingCredentialIds: List<String?>,
  val intentToRetain: Map<String?, Boolean?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PresentationRequestDto {
      val interactionId = pigeonVar_list[0] as String
      val verifierName = pigeonVar_list[1] as String
      val verifierUrl = pigeonVar_list[2] as String
      val verifierLogo = pigeonVar_list[3] as String?
      val requestedClaims = pigeonVar_list[4] as List<RequestedClaimDto?>
      val matchingCredentialIds = pigeonVar_list[5] as List<String?>
      val intentToRetain = pigeonVar_list[6] as Map<String?, Boolean?>?
      return PresentationRequestDto(interactionId, verifierName, verifierUrl, verifierLogo, requestedClaims, matchingCredentialIds, intentToRetain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      interactionId,
      verifierName,
      verifierUrl,
      verifierLogo,
      requestedClaims,
      matchingCredentialIds,
      intentToRetain,
    )
  }
}

/**
 * Presentation submission
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PresentationSubmissionDto (
  val interactionId: String,
  val credentialId: String,
  val selectedClaims: List<String?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PresentationSubmissionDto {
      val interactionId = pigeonVar_list[0] as String
      val credentialId = pigeonVar_list[1] as String
      val selectedClaims = pigeonVar_list[2] as List<String?>
      return PresentationSubmissionDto(interactionId, credentialId, selectedClaims)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      interactionId,
      credentialId,
      selectedClaims,
    )
  }
}

/**
 * Result wrapper for operations
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OperationResult (
  val success: Boolean,
  val error: String? = null,
  val data: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OperationResult {
      val success = pigeonVar_list[0] as Boolean
      val error = pigeonVar_list[1] as String?
      val data = pigeonVar_list[2] as Map<String?, Any?>?
      return OperationResult(success, error, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      error,
      data,
    )
  }
}
private open class SsiApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DidDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CredentialDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InteractionDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RequestedClaimDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PresentationRequestDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PresentationSubmissionDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OperationResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DidDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CredentialDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is InteractionDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RequestedClaimDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PresentationRequestDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PresentationSubmissionDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is OperationResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Main SSI API for native platform communication
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SsiApi {
  /** Initialize the SSI SDK */
  fun initialize(callback: (Result<OperationResult>) -> Unit)
  /** Get SDK version */
  fun getVersion(): String
  /** Create a new DID */
  fun createDid(method: String, keyType: String, callback: (Result<DidDto?>) -> Unit)
  /** Get all DIDs */
  fun getDids(callback: (Result<List<DidDto>>) -> Unit)
  /** Get a specific DID by ID */
  fun getDid(didId: String, callback: (Result<DidDto?>) -> Unit)
  /** Delete a DID */
  fun deleteDid(didId: String, callback: (Result<Boolean>) -> Unit)
  /** Get all credentials */
  fun getCredentials(callback: (Result<List<CredentialDto>>) -> Unit)
  /** Get a specific credential by ID */
  fun getCredential(credentialId: String, callback: (Result<CredentialDto?>) -> Unit)
  /** Accept a credential offer */
  fun acceptCredentialOffer(offerId: String, holderDidId: String?, callback: (Result<CredentialDto?>) -> Unit)
  /** Delete a credential */
  fun deleteCredential(credentialId: String, callback: (Result<Boolean>) -> Unit)
  /** Check credential status */
  fun checkCredentialStatus(credentialId: String, callback: (Result<String>) -> Unit)
  /** Process a presentation request (returns detailed request info) */
  fun processPresentationRequest(url: String, callback: (Result<PresentationRequestDto?>) -> Unit)
  /** Submit a presentation with selected claims */
  fun submitPresentationWithClaims(submission: PresentationSubmissionDto, callback: (Result<Boolean>) -> Unit)
  /** Submit a presentation (legacy method - kept for compatibility) */
  fun submitPresentation(interactionId: String, credentialIds: List<String>, callback: (Result<Boolean>) -> Unit)
  /** Reject a presentation request */
  fun rejectPresentationRequest(interactionId: String, callback: (Result<Boolean>) -> Unit)
  /** Get interaction history */
  fun getInteractionHistory(callback: (Result<List<InteractionDto>>) -> Unit)
  /** Export backup */
  fun exportBackup(callback: (Result<Map<String?, Any?>>) -> Unit)
  /** Import backup */
  fun importBackup(backupData: String, callback: (Result<Boolean>) -> Unit)
  /** Get supported DID methods */
  fun getSupportedDidMethods(callback: (Result<List<String>>) -> Unit)
  /** Get supported credential formats */
  fun getSupportedCredentialFormats(callback: (Result<List<String>>) -> Unit)
  /** Uninitialize SDK */
  fun uninitialize(callback: (Result<Boolean>) -> Unit)
  /**
   * Handle authorization response from EUDI issuer
   * Called when the app receives the authorization callback deep link
   */
  fun handleAuthorizationCallback(authorizationResponseUri: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Get debug logs from the native SDK
   * Returns the last 1000 lines of logs for debugging
   */
  fun getDebugLogs(callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by SsiApi. */
    val codec: MessageCodec<Any?> by lazy {
      SsiApiPigeonCodec()
    }
    /** Sets up an instance of `SsiApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SsiApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<OperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.createDid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val methodArg = args[0] as String
            val keyTypeArg = args[1] as String
            api.createDid(methodArg, keyTypeArg) { result: Result<DidDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getDids$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDids{ result: Result<List<DidDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getDid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val didIdArg = args[0] as String
            api.getDid(didIdArg) { result: Result<DidDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.deleteDid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val didIdArg = args[0] as String
            api.deleteDid(didIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCredentials{ result: Result<List<CredentialDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getCredential$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialIdArg = args[0] as String
            api.getCredential(credentialIdArg) { result: Result<CredentialDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.acceptCredentialOffer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offerIdArg = args[0] as String
            val holderDidIdArg = args[1] as String?
            api.acceptCredentialOffer(offerIdArg, holderDidIdArg) { result: Result<CredentialDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.deleteCredential$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialIdArg = args[0] as String
            api.deleteCredential(credentialIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.checkCredentialStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialIdArg = args[0] as String
            api.checkCredentialStatus(credentialIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.processPresentationRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.processPresentationRequest(urlArg) { result: Result<PresentationRequestDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.submitPresentationWithClaims$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val submissionArg = args[0] as PresentationSubmissionDto
            api.submitPresentationWithClaims(submissionArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.submitPresentation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val interactionIdArg = args[0] as String
            val credentialIdsArg = args[1] as List<String>
            api.submitPresentation(interactionIdArg, credentialIdsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.rejectPresentationRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val interactionIdArg = args[0] as String
            api.rejectPresentationRequest(interactionIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getInteractionHistory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInteractionHistory{ result: Result<List<InteractionDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.exportBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.exportBackup{ result: Result<Map<String?, Any?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.importBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val backupDataArg = args[0] as String
            api.importBackup(backupDataArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getSupportedDidMethods$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSupportedDidMethods{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getSupportedCredentialFormats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSupportedCredentialFormats{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.uninitialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.uninitialize{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.handleAuthorizationCallback$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val authorizationResponseUriArg = args[0] as String
            api.handleAuthorizationCallback(authorizationResponseUriArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ssi.SsiApi.getDebugLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDebugLogs{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
