# Uncomment this line to define a global platform for your project
platform :ios, '16.0'  # EUDI Wallet Kit requires iOS 16.0 or higher

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # EUDI Wallet Kit must be added via Swift Package Manager in Xcode
  # See: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit
  #
  # To add the EUDI SDK:
  # 1. Open ios/Runner.xcworkspace in Xcode
  # 2. Select the Runner project
  # 3. Go to "Package Dependencies" tab
  # 4. Click "+" to add package
  # 5. Enter URL: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit.git
  # 6. Select version: 0.19.4 (or latest compatible version)
  # 7. Add to Runner target
  #
  # Note: The SDK requires iOS 16.0+ (already configured above)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
